config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about_us", to: "pages#about_us"
  get "how_it_works", to: "pages#how_it_works"
  resources :items do
    resources :bookings, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    collection do
      get :my_items, to: 'items#my_items'
      get :my_favorite_items, to: 'items#my_favorite_items'
    end
    member do
      post :toggle_favorite, to: "items#toggle_favorite"
    end
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  get "/bookings/:id/cancel", to: "bookings#cancel", as: "booking_cancel"
  get "/bookings/:id/accept", to: "bookings#accept", as: "booking_accept"
  get "/bookings/:id/decline", to: "bookings#decline", as: "booking_decline"
  resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  resources :favourites
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews
  belongs_to :user
  belongs_to :item

  validates :start_date, :end_date, presence: true
  validate :min_days_rent
  enum status: { pending: 0, accepted: 1, declined: 2, cancelled: 3 }

  def total_price
    number_of_days = end_date - start_date
    return (item.price * number_of_days).to_i
  end

  def min_days_rent
    if start_date && end_date && (end_date - start_date).to_i < item.min_days_rent
      errors.add(:end_date, "must be at least #{item.min_days_rent} days after the start date")
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # before_action :set_booking, only: [:new, :create, :edit, :update, :destroy]

  def index
    @bookings = policy_scope(Booking).all
    %w[pending accepted declined cancelled].each do |status|
      instance_variable_set("@#{status}_bookings_count", policy_scope(Booking).send(status).count)
    end
    booking_ids = @bookings.pluck(:item_id)
    @items = []
    booking_ids.each { |id| @items << Item.find(id) }
    @markers = @items.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude
        #info_window: render_to_string(partial: "popup", locals: {item: item})
      }
    end
  end

  # the Booking Show page is not necessary
  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @item = Item.find(params[:item_id])
    @booking = @item.bookings.new
    authorize @item
  end

  def create
    @item = Item.find(params[:item_id])
    @booking = @item.bookings.new(booking_params)
    @booking.user = current_user

    authorize @item

    if @booking.save
      ItemMailer.booking(@item.user, @booking).deliver_now
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])

    authorize @booking

    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @booking = @item.bookings.destroy(params[:id])

    authorize @item
    redirect_to item_bookings_path, status: :see_other
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update status: 'accepted'
    redirect_to bookings_path
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update status: 'declined'
    redirect_to bookings_path
  end

  def cancel
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update status: 'cancelled'
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  # def set_booking
  #   @item = Item.find(params[:item_id])
  # end

end

app/views/bookings/edit.html.erb
<%= simple_form_for([@item, @booking]) do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/bookings/index.html.erb
<div class="main-container">
  <div class="container-bookings row">
    <div class="col-6 text-left">
      <% %w[pending accepted declined cancelled].each do |status| %>
        <% bookings_by_status = @bookings.select { |booking| booking.status == status } %>
        <% if bookings_by_status.present? %>
          <% count = bookings_by_status.size %>
          <% concat(content_tag(:h2, "#{status}: #{count} #{count == 1 ? 'booking' : 'bookings'}", class: "status-title")) %>

          <div class="container-bookings-items">
            <% bookings_by_status.each do |booking| %>
              <div class="booking-item">
                <div class="booking-item-top">
                  <%= booking.item.name %>
                </div>
                <div class="booking-item-bottom">
                  <div>
                    <p class="description"><%= booking.item.description %></p>
                    <p class="rental-dates"><strong>Rental Dates:</strong> <%= booking.start_date.strftime("%d %b %Y") %> - <%= booking.end_date.strftime("%d %b %Y") %></p>
                    <p class="rental-price"><strong>Rental Price:</strong> <%= booking.total_price %> euros</p>
                    <p class="booking-status"><strong>Booking Status:</strong> <%= booking.status %></p>
                  </div>
                  <div class="booking-actions">
                    <%= link_to "Update", edit_booking_path(booking), class: "btn btn-danger btn btn-m", style: "border-radius: 20px; background-color: #ff3d3d" %>
                    <%= link_to "Review", new_item_booking_review_path(booking.item_id, booking), class: "btn btn-danger btn-m", style: "border-radius: 20px; background-color: #ff3d3d" %>
                    <%= link_to "Cancel", booking_cancel_path(booking), class: "btn btn-outline-danger btn-m", style: "border-radius: 20px;", data: {turbo_confirm: "Are you sure you want to cancel the booking?"} %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-6">
      <div data-controller="map"
          id='map'
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
          data-map-markers-value="<%= @markers.to_json %>"
          style='width: 100%; height: 93vh; position: sticky; top: 70px; z-index: 0; border-radius: 10px;'>
        </div>
    </div>
  </div>
</div>


<style>

.booking-item-top{
  background-color: #ccc;
  color: black;
  padding: 20px;
  font-size: 25px;
}

.booking-item-bottom{
  display: flex;
  justify-content: space-between;
  background-color: black;
  padding: 20px;
  color: white;
}

.booking-name{
  height: 50px;
  background-color: black;
  padding-top: 10px;
}

h4{
  background-color: #ff3d3d;
  margin-top: 3px;
}

.main-container{
  padding: 1px;
  background-color:#e6e6e6;
}

.btn-outline-danger:hover{
  background-color: #ff3d3d;

}

.status-title{
  color: #111111;
  text-transform: capitalize;
  letter-spacing: -3px;

}
  .container-bookings {
    margin-left: auto;
    margin-right: auto;
    margin-top: 50px;
    width: 90%;
  }

  .container-bookings-items {
    margin-top: 0px;
  }

  .booking-item {
    border-radius: 10px;
    align-items: center;
    overflow: hidden;
    margin: 15px;
    background-color: #ffffff;
  }

  .booking-item img {
    width: 100px;
    height: 100px;
    object-fit: cover;
    margin-right: 20px;
  }

  .booking-details {
    margin: 0px;
    flex: 1;
  }

  .booking-details h5 {
    margin: 0;
    margin-bottom: 5px;
    font-size: 1.25rem;
  }

  .booking-details p {
    margin: 0;
    margin-bottom: 5px;
  }

  .booking-actions {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
  }

  .booking-actions a {
    margin: 5px 0;
  }
</style>

app/views/bookings/new.html.erb
<div style="background-color: #ec7d83; background-image: url(<%= asset_path 'wallpapers/bookingbackground2.png' %>); background-position: center center; background-repeat: no-repeat; background-size: cover; opacity: 0.8; display: flex; align-items: center;">
  <div class="new-booking-container" style="display: flex; flex-direction: column; align-items: center; margin: 150px auto; background-color: lightgrey; width: 50%; padding: 20px; background-color: rgba(211, 211, 211, 0.8); border-radius: 20px;">
    <h2>Booking <%= @item.name %></h2>
    <p><%= @item.description %></p>
    <div class="item-photo" style="margin: 20px;">
      <%= cl_image_tag @item.photos.first.key, class: "cl-img" %>
    </div>
    <div class="container" style="display: flex; flex-direction: column;">
    <%= simple_form_for ([@item, @booking]) , data: { controller: 'flatpickr' } do |f| %>
      <div class="form-fields" style="display: flex; flex-direction: column; align-self: flex-end;">
        <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id: 'end_time' } %>
        <%= f.submit 'Book', class: "submit-book" %>
      </div>
    <% end %>
  </div>
</div>



<style>

  .new-booking-container {
  width: 40%;
  }

  .cl-img {
    max-width: 120%;
  }

  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  input[type="text"] {
    border-radius: 20px;
    border: 2px solid white;
    padding: 10px;
    margin-bottom: 10px;
    background-color: black;
    color: white;
  }

  .submit-book {
    border-radius: 20px;
    border: none;
    background-color: #ff7070;
    color: white;
    padding: 10px 20px;
    margin-top: 10px;
    align-self: flex-end;
  }

  .new-booking-container {
    margin: 150px auto;
  }
</style>

app/views/bookings/show.html.erb
<p>Show page not necessary in our User Story!</p>