config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about_us", to: "pages#about_us"
  get "how_it_works", to: "pages#how_it_works"
  resources :items do
    resources :bookings, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    collection do
      get :my_items, to: 'items#my_items'
      get :my_favorite_items, to: 'items#my_favorite_items'
    end
    member do
      post :toggle_favorite, to: "items#toggle_favorite"
    end
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  get "/bookings/:id/cancel", to: "bookings#cancel", as: "booking_cancel"
  get "/bookings/:id/accept", to: "bookings#accept", as: "booking_accept"
  get "/bookings/:id/decline", to: "bookings#decline", as: "booking_decline"
  resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  resources :favourites
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/views/shared/_button.html.erb
<div class="neon__button">
<a href="#">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Neon button
    </a>
    <a href="#">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Neon button
    </a>
    <a href="#">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Neon button
    </a>
</div>

app/views/shared/_category_cards.html.erb
  <article class="card">
    <%= image_tag "categories/bike_category.jpeg",
      class: "card__background",
      alt: "Bike category"
    %>
    <div class="card__content | flow">
      <div class="card__content--container | flow">
        <h2 class="card__title">Bikes</h2>
        <p class="card__description">
          Looking for an eco-friendly way to get around town? Or you simply want to have a ride? Check out our bike category and discover a new way to commute.
        </p>
      </div>
      <button class="card__button">
        <a href="<%= items_path(category: "Drones") %>" style="color: #e6e6e6; font-family: $special-font">Explore</a>
      </button>
    </div>
  </article>
</div>
<div class="col-sm-6 col-md-12 col-lg-6">
  <article class="card">
    <%= image_tag "categories/drones_category.jpeg",
      class: "card__background",
      alt: "Drones category"
    %>
    <div class="card__content | flow">
      <div class="card__content--container | flow">
        <h2 class="card__title">Drones</h2>
        <p class="card__description">
          Take your photography to new heights. Browse our drone category to capture stunning aerial shots of your city.
        </p>
      </div>
      <button class="card__button">
        <a href="<%= items_path(category: "Drones") %>" style="color: #e6e6e6;">Explore</a>
      </button>
    </div>
  </article>
</div>
<div class="col-sm-6 col-md-12 col-lg-6 mb-4">
  <article class="card">
    <%= image_tag "categories/tools_category.jpeg",
      class: "card__background",
      alt: "HomeHub category"
    %>
    <div class="card__content | flow">
      <div class="card__content--container | flow">
        <h2 class="card__title">HomeHub</h2>
        <p class="card__description">
          DIY made easy with HomeHub. Browse our collection of tools and home items to find everything you need to get the job done. Borrow what you need and reduce consumption while saving money.
        </p>
      </div>
      <button class="card__button">
        <a href="<%= items_path(category: "Drones") %>" style="color: #e6e6e6;">Explore</a>
      </button>
    </div>
  </article>
</div>
<div class="col-sm-6 col-md-12 col-lg-6 mb-4">
  <article class="card">
    <%= image_tag "categories/photo_category.jpeg",
      class: "card__background",
      alt: "LensLend category"
    %>
    <div class="card__content | flow">
      <div class="card__content--container | flow">
        <h2 class="card__title">LensLend</h2>
        <p class="card__description">
          Join the photography sharing community with LensLend. Borrow lenses and equipment to capture the perfect shot and share your own gear to help others do the same.
        </p>
      </div>
      <button class="card__button">
        <a href="<%= items_path(category: "Drones") %>" style="color: #e6e6e6;">Explore</a>
      </button>
    </div>
  </article>

<!--<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
<div class="row bootstrap snippets bootdeys">
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'photog.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Camera & Photography</h3>
                    <div class="circle-red"><i class="fa-solid fa-camera"></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'audio.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Audio & Visual</h3>
                    <div class="circle-red"><i class="fa-solid fa-microphone"></i></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'music.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Musical Instruments</h3>
                    <div class="circle-red"><i class="fa-solid fa-guitar"></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'transportation.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Transport</h3>
                    <div class="circle-red"><i class="fa-solid fa-van-shuttle"></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'projectors.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Projector</h3>
                    <div class="circle-red"><i class="fa-solid fa-tv"></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'electronics.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Electronics</h3>
                    <div class="circle-red"><i class="fa-solid fa-laptop"></i></div>
                </a>
            </div>
        </div>
    </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'scooter.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Electric Scooters</h3>
                    <div class="circle-red"><i class="fa-solid fa-bicycle"></i></div>
                </a>
            </div>
        </div>
    </div>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
        <div class="card">
            <div class="thumbnail">
                <%= image_tag 'machine.jpg' %>
                <a href="#" class="thumb-cover"></a>
                <div class="details">
                    <div class="authors-container">
                        <div class="author">
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="card-info">
                <a href="#">
                    <h3>Electronics</h3>
                    <div class="circle-red"><i class="fa-solid fa-hat-wizard"></i></div>
                </a>
            </div>
        </div>
    </div>

</div>
</div>-->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-6">
          <!-- Contact Info-->
          <section class="widget widget-light-skin">
            <h3 class="widget-title">Get In Touch With Us</h3>
            <a href="mailto:team@allshare.online">
            <p class="text-white">E-Mail: team@allshare.online</p>
            </a>
            <%= render "shared/social_media" %>

          </section>
        </div>
        <div class="col-lg-3 col-md-6">
          <!-- Mobile App Buttons-->
          <section class="widget widget-light-skin">
            <h3 class="widget-title">Our Mobile App</h3><a class="market-button apple-button mb-light-skin" href="#"><span class="mb-subtitle">Download on the</span><span class="mb-title">App Store</span></a><a class="market-button google-button mb-light-skin" href="#"><span class="mb-subtitle">Download on the</span><span class="mb-title">Google Play</span></a>
          </section>
        </div>
        <div class="col-lg-3 col-md-6">
          <!-- About Us-->
          <section class="widget widget-links widget-light-skin">
            <h3 class="widget-title">About...</h3>
            <ul>
              <li><%= link_to "About us", about_us_path %></li>
              <li><%= link_to "How it works", how_it_works_path %></li>
              <li><a href="#">services</a></li>
            </ul>
          </section>
        </div>
        <div class="col-lg-3 col-md-6">
          <!-- Account / Shipping Info-->
          <section class="widget widget-links widget-light-skin">
            <h3 class="widget-title">Account Info</h3>
            <ul>
              <li><a href="#">Your Account/ Log In/ Sign Up</a></li>
              <li> <form class="subscribe-form" action="#" method="post" target="_blank" novalidate="">
                    <div class="clearfix">
                    <div class="input-group input-light" style="float: left;">
                    <input class="form-control" type="email" name="EMAIL" placeholder="Subscribe to our newsletter" style="float: left; width: 220px; max-width: 250px;">
                    <button class="btn btn-primary mt-2" type="submit" style="float: left; margin-left: 0px; margin-top: 5px;">Subscribe
                    </button>
              </li>
              </div>

            </div>
          </form>
            </ul>
          </section>

        </div>
      </div>
      <hr class="hr-light mt-2 margin-bottom-2x">
    </div>
  </footer>

<style>
ul {
  list-style: none;
}
</style>

app/views/shared/_home_navbar.html.erb
<div class="navbar-home navbar-expand-sm navbar-light navbar-lewagon banner-navbar" style="background-color: rgba(0, 0, 0, 0); z-index: 1;">
  <div class="container-fluid" style="display: flex; justify-content: space-between;">
    <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logos/logo-pink-trans-care2.png", style: "width: 300px; height: 100px;" %>
<% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "How it works", how_it_works_path, class: "nav-link", style: "color: white; margin-right: 10px;" %>
          </li>
          <li class="nav-item active">
            <%= link_to "About us", about_us_path, class: "nav-link", style: "color: white; margin-right: 10px;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "/chatrooms/1", class: "nav-link", style: "color: white; margin-right: 10px;" %>
          </li>
          <li class="nav-item">
            <%# <p class="dropdown-item nav-link" style="color: white;"><%= current_user.first_name %></p>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "My items", my_items_items_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "My favorite items", my_favorite_items_items_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item", style: "color: black;" %>
            </div>
          </li>
        <% else %>
          <div class="home-links">
            <li>
              <%= link_to "How it works", how_it_works_path, class: "nav-link", style: "color: white;" %>
            </li>
            <li>
              <%= link_to "About us", about_us_path, class: "nav-link", style: "color: white;" %>
            </li>
          </div>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
  </div>

<style>
  .dropdown-menu {
    background-color: #F5F5F5;
  }
</style>

<script>

  function showLogin() {
    document.getElementById("overlay").style.display = "block";
    document.getElementById("login-form-wrapper").style.display = "block";
  }

  function hideLogin() {
    document.getElementById("overlay").style.display = "none";
    document.getElementById("login-form-wrapper").style.display = "none";
  }

  $(document).on('click', '.login-link', function(event) {
    event.preventDefault();
    $('#login-popup').fadeIn();
  });

  $(document).on('click', '#login-popup', function(event) {
    if (event.target === this) {
      $(this).fadeOut();
    }
  });

  $(function() {
      $('form#new_user_session').on('ajax:success', function(event) {
        var loginButton = $('.login-link');
        loginButton.text('Logged in');
        loginButton.attr('href', '<%= destroy_user_session_path %>');
        $('#login-popup').fadeOut();
      });
    });

</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background-color: black;">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logos/logo-pink-trans-care2.png", style: "width: 300px; height: 100px;" %>
    <% end %>

    <div class="d-flex justify-content-between search-form">
      <%= render "shared/search_form" %>
      <button type="button" class="shiny-btn">
        <a href="<%= new_item_path %>" class="list-item-link" style="color: black; text-decoration: none;">List item</a>
      </button>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "How it works", how_it_works_path, class: "nav-link", style: "color: white;" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "/chatrooms/1", class: "nav-link", style: "color: white;" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My bookings", bookings_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "My items", my_items_items_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "My favorite items", my_favorite_items_items_path, class: "dropdown-item", style: "color: black;" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item", style: "color: black;" %>
            </div>
          </li>
        <% else %>
          <div class="home-links">
            <li>
              <%= link_to "How it works", how_it_works_path, class: "nav-link", style: "color: white;" %>
            </li>
            <li>
              <%= link_to "About us", about_us_path, class: "nav-link", style: "color: white;" %>
            </li>
          </div>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<style>
  .dropdown-menu {
    background-color: #F5F5F5;
  }
</style>

app/views/shared/_profile_cards.html.erb
<!--Bootstrap CDN-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" type="text/css" />

<!--CDN End Here-->
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-md-3">
      <div class="profile-card">
        <div class="profile-img">
        <img src="assets/s.png" alt="Team Image" />
        </div>
        <div class="profile-content">
          <h2 class="title">Stephan
            <span>Knorn</span>
          </h2>
          <ul class="social-link">
            <li><a href="#" class="fa fa-facebook"></a></li>
            <li><a href="#" class="fa fa-google"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-youtube"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="profile-card">
        <div class="profile-img">
        <img src="assets/c.png" alt="Team Image" />
        </div>
        <div class="profile-content">
          <h2 class="title">Ciprian
            <span>Crisan</span>
          </h2>
          <ul class="social-link">
            <li><a href="#" class="fa fa-facebook"></a></li>
            <li><a href="#" class="fa fa-google"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-youtube"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="profile-card">
        <div class="profile-img">
          <%= image_tag "l.png" %>
        </div>
        <div class="profile-content">
          <h2 class="title">Lorenzo
            <span>Bertolino</span>
          </h2>
          <ul class="social-link">
            <li><a href="#" class="fa fa-facebook"></a></li>
            <li><a href="#" class="fa fa-google"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-youtube"></a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-3">
      <div class="profile-card">
        <div class="profile-img">
          <%= image_tag "f.png" %>
        </div>
        <div class="profile-content">
          <h2 class="title">Fahad
            <span>Jibran</span>
          </h2>
          <ul class="social-link">
            <li><a href="#" class="fa fa-facebook"></a></li>
            <li><a href="#" class="fa fa-google"></a></li>
            <li><a href="#" class="fa fa-twitter"></a></li>
            <li><a href="#" class="fa fa-youtube"></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<div class="search-form">
  <%= form_with url: items_path, method: :get, class: "d-flex" do |form| %>
    <div class="search-input-container">
      <div class="search-icon-container">
        <i class="fas fa-search search-icon"></i>
      </div>
      <%= form.text_field :query,
        value: params[:query],
        class: "search-input",
        placeholder: "Search items..."
      %>
    </div>
    <%= form.submit "Search", class: "search-button" %>
  <% end %>
</div>

app/views/shared/_social_media.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="">
  <div class="container">
    <i class="fa fa-twitter" id="twitter"></i>
    <i class="fa-brands fa-square-instagram" id="instagram"></i>
    <i class="fa fa-facebook-square" id="facebook"></i>
  </div>

app/views/shared/_testimonial.html.erb
<div class="container">
<div class="row">
    <div class="col-md-4 margin-btm-20">
        <div class="quote dark">
            <blockquote>
                <p>
                    "This is my second rental with Antonio - great equipment, great price and brilliant service!"
                </p>
            </blockquote>
        </div>
        <div class="quote-footer text-right">
            <div class="quote-author-img">
                <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="">
            </div>
            <div class="product-rating mb-2">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star mr-0"></i>
                    </div>
            <h4>Rakesh Sharma</h4>
            <p>
                <strong>London</strong>
            </p>
        </div>
    </div><!--colored quote box col-->
    <div class="col-md-4 margin-btm-20">
        <div class="quote green">
            <blockquote>
                <p>
                    "Mario was a super nice, chilled out guy and his gear was perfect for my project. Highly recommend."
                </p>
            </blockquote>
        </div>
        <div class="quote-footer text-right">
            <div class="quote-author-img">
                <img src="https://bootdey.com/img/Content/avatar/avatar6.png" alt="">
            </div>
              <div class="product-rating mb-8">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star mr-0"></i>
                    </div>

            <h4>Stephan K</h4>
            <p>
                <strong>Berlin</strong>
            </p>
        </div>
    </div><!--colored quote box col-->
    <div class="col-md-4 margin-btm-20">
        <div class="quote dark">
            <blockquote>
                <p>
                    "Excellent communication, absolutely lovely people, amazing gimbal and an incredibly smooth process!"
                </p>
            </blockquote>
        </div>
        <div class="quote-footer text-right">
            <div class="quote-author-img">
                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="">
            </div>
            <div class="product-rating mb-2">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star mr-0"></i>
                    </div>
            <h4>Lorenzo B</h4>
            <p>
                <strong>Milan</strong>
            </p>
        </div>
    </div><!--colored quote box col-->
</div><!--testimonials row-->
</div>

<div class="container">
            <div class="row">
                <div class="col-md-4 margin-btm-20">
                    <div class="quote dark">
                        <blockquote>
                            <p>
                                "Brilliant guy and very easy to deal with. Great kit and really easy to collect and return equipment."
                            </p>
                        </blockquote>
                    </div>
                    <div class="quote-footer text-right">
                        <div class="quote-author-img">
                            <img src="https://bootdey.com/img/Content/avatar/avatar4.png" alt="">
                        </div>
                        <div class="product-rating mb-2">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>

                        <i class="fas fa-star"></i>
                        <i class="fas fa-star mr-0"></i>
                    </div>
                        <h4>Adam</h4>
                        <p>
                            <strong>Manchester</strong>
                        </p>
                    </div>
                </div><!--colored quote box col-->
                <div class="col-md-8 margin-btm-20">
                    <div class="quote green">
                        <blockquote>
                            <p>
                                I highly recommend to experience the AllShare. The client support is really caring about your need and they are here to support you. I m very happy to have been one of their clients and I am monthly renting their camera. Try it and you will love them as I am. Their camera is very professional and useful for personal needs.
                            </p>
                        </blockquote>
                    </div>
                    <div class="quote-footer text-right">
                        <div class="quote-author-img">
                            <img src="https://bootdey.com/img/Content/avatar/avatar5.png" alt="">
                        </div>
                        <div class="product-rating mb-2">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star mr-0"></i>
                    </div>
                        <h4>Cipirian</h4>
                        <p>
                            <strong>Paris</strong>
                        </p>
                    </div>
                </div><!--colored quote box col-->
            </div><!--testimonials row-->
        </div>