config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "about_us", to: "pages#about_us"
  get "how_it_works", to: "pages#how_it_works"
  resources :items do
    resources :bookings, only: [:new, :create] do
      resources :reviews, only: [:new, :create]
    end
    collection do
      get :my_items, to: 'items#my_items'
      get :my_favorite_items, to: 'items#my_favorite_items'
    end
    member do
      post :toggle_favorite, to: "items#toggle_favorite"
    end
  end
  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  get "/bookings/:id/cancel", to: "bookings#cancel", as: "booking_cancel"
  get "/bookings/:id/accept", to: "bookings#accept", as: "booking_accept"
  get "/bookings/:id/decline", to: "bookings#decline", as: "booking_decline"
  resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  resources :favourites
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user
  has_many_attached :photos

  validates :category, :name, :description, :postal_code, :quantity, :min_days_rent, :price, presence: true

  geocoded_by :postal_code
  after_validation :geocode, if:
  :will_save_change_to_postal_code?

  acts_as_favoritable

  include PgSearch::Model

  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true }
    }
end

#
#validates :picture, :category, :name, :description, :postal_code, :quantity, :min_days_rent, :price, presence: true
#when I add the picture validation I can't create a new Item from the List an item page
#when I add the photos validation I can't seed
# Explanation

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if params[:query].present?
      @items = policy_scope(Item).search_by_name_and_category(params[:query]).limit(10).offset(params[:page].to_i * 10)
    elsif params[:category].present?
      @items = policy_scope(Item).where(category: params[:category]).limit(10).offset(params[:page].to_i * 10)
    else
      @items = policy_scope(Item).all.limit(10).offset(params[:page].to_i * 10)
    end

    # @items = Item.limit(10).offset(params[:page].to_i * 10)

    @markers = @items.geocoded.map do |item|
      {
        lat: item.latitude,
        lng: item.longitude,
        info_window: render_to_string(partial: "popup", locals: {item: item})
      }
    end
  end

  def my_items
    @my_items = Item.where(user: current_user)
    authorize @my_items
  end

  def my_favorite_items
    @my_favorite_items = current_user.all_favorites
    authorize @my_favorite_items
  end

  def new
    @item = Item.new
    authorize @item
  end

  def show
    @item = Item.find(params[:id])
    @reviews = @item.reviews
    authorize @item
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    authorize @item

    if @item.save
      ItemMailer.confirmation(@item.user).deliver_now
      redirect_to item_path(@item)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    @item.update(item_params)
    redirect_to items_path
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  def toggle_favorite
    @item = Item.find(params[:id])
    current_user.favorited?(@item) ? current_user.unfavorite(@item) : current_user.favorite(@item)
  end

  private

  def item_params
    params.require(:item).permit(
      :category, :name, :description, :postal_code, :quantity, :min_days_rent, :price, photos: []
    )
  end
end

app/views/items/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(@item) %>" data-id="<%= @item.id %>">
  <i class="fas fa-heart like-button" style="color: red;"></i>
</div>

app/views/items/_popup.html.erb
<div class="popup">
  <%= link_to item_path(item), style: 'text-decoration: none' do %>
    <% if item.picture%>
      <%= image_tag item.picture, class: "popup-img" %>
    <% else %>
      <% item.photos.each do |photo| %>
        <%= cl_image_tag photo.key, class: "popup-img" %>
      <% end %>
    <% end %>
    <h1><%= item.name %></h1>
    <h3>Postal code: <%= item.postal_code %></h3>
  <% end %>
</div>

<style>
  .popup {
    border: 1px solid #ccc;
    border-radius: 5px;
    padding: 10px;
    margin: 10px;
    width: 100px;
    box-shadow: 2px 2px 2px #ccc;
  }

  .popup-img {
    width: 100%;
    height: auto;
    border-radius: 5px;
    margin-bottom: 10px;
  }

  .popup h1 {
    font-size: 14px;
    margin-bottom: 2px;
    text-decoration: none;
  }

  .popup h3 {
    font-size: 8px;
    line-height: 1.5;
    text-decoration: none;
  }
</style>

app/views/items/edit.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.input :category %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :postal_code %>
  <%= f.input :quantity %>
  <%= f.input :min_days_rent %>
  <%= f.input :price %>
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<div class="box">
  <div class="content-index">
    <div class="col-left">
      <% @items.each do |item| %>
        <div class="card-index">
          <%= link_to item_path(item) do %>
            <%= cl_image_tag item.photos.first.key, class: "cl-img" %>
            <div class="card-index-body">
              <div class="card-index-body-up">
                <h2 class="card-index-title" style="margin-bottom: 0;"><%= item.name %></h2>
                <h3 class="card-index-category"><%= item.category %></h3>
                <p style="color: #00264C; overflow: hidden; overflow: auto;"><%= item.description %></p>
              </div>
              <div class="card-index-body-down">
                <div class="card-index-details">
                  <div class="item-index-price" style="width: 100%">
                    <p style="font-size: 20px;  color: #00264C;"><%= "€" + item.price.round.to_s %>/day</p>
                    <p style="font-size: 12px; margin-bottom: 0; color: gray;">*Plan ahead: <%= item.min_days_rent %> minimum rental period</p>
                  </div>
                </div>
                <div class="item-index-btn">
                  <% unless policy(item).owner? %>
                    <button type="button" class="book">
                      <%= link_to "Book", new_item_booking_path(item) %>
                    </button>
                  <% end %>
                </div>
              </div>
            </div>
            <%= link_to toggle_favorite_item_path(item),
                        class: "favorite-item-link",
                        data: {turbo_method: :post} do %>
              <% if current_user.favorited?(item) %>
                <i class="fas fa-heart" style="color: red;"></i>
              <% else %>
                <i class="far fa-heart" aria-hidden="false" style="color: red;"></i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <div class="index-pagination">
        <% (0..4).each do |page_num| %>
          <% if params[:page].to_i == page_num %>
            <div class="page-num current-page"><%= page_num + 1 %></div>
          <% elsif page_num < 5 %>
            <%= link_to page_num + 1, items_path(page: page_num), class: "page-num" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-right">
      <div data-controller="map"
        id='map'
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-markers-value="<%= @markers.to_json %>"
        style='width: 100%; height: 93vh; position: sticky; top: 0; z-index: 0;'>
      </div>
    </div>
  </div>
</div>

app/views/items/my_favorite_items.html.erb
<% if @my_favorite_items.empty? %>
  <h2>My favorite items</h2>
  <p>Tap the heart to unlike</p>
<% else %>
  <div class="myfavitems-main">
    <div class="myfavitems-main-left">
      <p style="font-size: 36px; font-weight: bold; color: #111111;">My favorite items</p>
      <p style="font-size: 24px; color: #111111;">You have <%= @my_favorite_items.count %> favorite items</p>
      <div class="left-wall">
        <%= image_tag("wallpapers/pages/myitems_fav.png", alt: "My fav items", size: "300x300") %>
      </div>
    </div>
    <div class="myfavitems-main-right">
      <% @my_favorite_items.each do |favorite| %>
        <div class="myfavitems-card">
          <div class="myfavitems-tumb">
            <%= link_to item_path(favorite.favoritable) do %>
              <% if favorite.favoritable.picture %>
                <%= image_tag favorite.favoritable.picture %>
              <% else %>
                <% favorite.favoritable.photos.each do |photo| %>
                  <%= cl_image_tag photo.key %>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <div class="myfavitems-details">
            <span class="myfavitems-category"><%= favorite.favoritable.category %></span>
            <h4><a href=""><%= link_to favorite.favoritable.name, item_path(favorite.favoritable) %></a></h4>
            <p><%= favorite.favoritable.description %></p>
            <div class="myfavitems-bottom-details">
              <div class="myfavitems-price"><%= "€" + favorite.favoritable.price.round.to_s %>/day</div>
            </div>
            <div class="myfavitems-links">
              <%= link_to item_path(favorite.favoritable) do %>
                <%= link_to toggle_favorite_item_path(favorite.favoritable),
                          class: "favorite-item-link",
                          data: {turbo_method: :post},
                          remote: true do %>
                  <% if current_user.favorited?(favorite.favoritable) %>
                    <i class="fas fa-heart"></i>
                  <% else %>
                    <i class="far fa-heart" aria-hidden="false"></i>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/my_items.html.erb
<div class="myitems-main">
  <div class="myitems-main-left">
    <p style="font-size: 36px; font-weight: bold; color: #111111;">My items</p>
    <p style="font-size: 24px; color: #111111;">You have <%= current_user.items.count %> listed items</p>
    <div class="left-wall">
      <%= image_tag("wallpapers/pages/myitems.png", alt: "My items", size: "300x300") %>
    </div>
  </div>
  <div class="myitems-main-right">
    <% @my_items.each do |item| %>
      <div class="myitems-card">
        <div class="myitems-tumb">
          <% item.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
        </div>
        <div class="myitems-details">
          <span class="myitems-category"><%= item.category %></span>
          <h4><a href=""><%= link_to item.name, item_path(item) %></a></h4>
          <p><%= item.description %></p>
          <div class="myitems-bottom-details">
            <div class="myitems-price"><%= "€" + item.price.round.to_s %>/day</div>
            <div class="myitems-links">
              <a href=""><i class="fa fa-heart"></i></a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!--
<div class="myitems-bar">
  <h2>My items</h2>
  <button type="button" class="shiny-btn">
    <a href="<%= new_item_path %>" class="list-item-link" style="color: black; text-decoration: none; margin: 10px 10px;">List item</a>
  </button>
</div>

<div class="myitems-main">
  <% @my_items.each do |item| %>
    <div class="myitems-card">
      <div class="myitems-tumb">
        <% item.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
      </div>
      <div class="myitems-details">
        <span class="myitems-category"><%= item.category %></span>
        <h4><a href=""><%= link_to item.name, item_path(item) %></a></h4>
        <p><%= item.description %></p>
        <div class="myitems-bottom-details">
          <div class="myitems-price"><%= "€" + item.price.round.to_s %>/day</div>
          <div class="myitems-links">
            <a href=""><i class="fa fa-heart"></i></a>
            <a href=""><i class="fa fa-shopping-cart"></i></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
-->

app/views/items/new.html.erb
<head>
  <link rel="stylesheet" href="/stylesheets/signinup">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="/javascript/controllers/signinupform.js"></script>
</head>
<div style="background-image: url(<%= asset_path 'wallpapers/wallpaper5.jpg' %>); background-position: center center; background-repeat: no-repeat; background-size: cover;">
  <div class="signup-form-container" style="display: flex; justify-content: center; flex-direction: row; align-items: center; width: 80%; background-color: lightgrey; padding: 50px; height: 90vh; min-height: 100vh; background: transparent; margin-left: 50px;">
    <div class="new-item-container" style="display: flex; justify-content: center; flex-direction: row; align-items: center; width: 80%;">
      <div class="form-inputs" style="display: flex; justify-content: center; align-items: center; width: 75%; max-width: 550px;">
        <%= simple_form_for(@item) do |f| %>
          <div class="field required">
            <%= f.input :photos, as: :file, input_html: { multiple: true, class: "text-input file-input" } %>
          </div>

          <div class="field required">
            <%= f.input :category,
              collection: ['Film & photography', 'Audio & visual', 'Projectors & screens', 'Drones', 'DJ equipment', 'Storage', 'Electronics', 'Transport', 'Party & Events', 'Sports', 'Home, office & garden', 'Clothing', 'Holiday & travel', 'Musical instruments', 'Kids & baby'],
              input_html: {class: "text-input", style: "background-color: black;"} %>
          </div>
          <div class="field required">
            <%= f.input :name, input_html: {class: "text-input", style: "background-color: black; color: white;"} %>
          </div>
          <div class="field required">
            <%= f.input :description, input_html: {class: "text-input", style: "background-color: black; color: white;"} %>
          </div>
          <div class="field required">
            <%= f.input :postal_code, input_html: {class: "text-input", style: "background-color: black; color: white;"} %>
          </div>
          <div class="field required">
            <%= f.input :quantity, input_html: { id: "item_quantity", class: "text-input", style: "background-color: black; color: white;" } %>
          </div>

          <div class="field required">
            <%= f.input :min_days_rent, input_html: { id: "item_min_days_rent", class: "text-input", style: "background-color: black; color: white;" } %>
          </div>

          <div class="field required">
            <%= f.input :price, input_html: { id: "item_price", class: "text-input", style: "background-color: black; color: white;" } %>
          </div>

          <div class="form-actions" style="display: flex; flex-direction: column; justify-content: center;">
            <button class="button" style="border-radius: 20px; width: 180px; height: 50px; display: flex; justify-content: center; align-items: center; margin: 20px; margin-left:45%;">
              <%= f.button :submit, "Upload", class: "button" %>
            </button>
          </div>
        <% end %>
      </div>
      <div id="preview-container" class="col-md-6">
        <div class="card">
          <div class="card-body">
            <img id="preview-image" class="card-img-top" height="300" width="400" src="#" alt="Image preview" style="display: none;">
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h1 id="preview-name"></h1>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><strong>Category:</strong> <span id="preview-category"></span></li>
              <li class="list-group-item"><strong>Description:</strong> <span id="preview-description"></span></li>
              <li class="list-group-item"><strong>Postal code:</strong> <span id="preview-postal-code"></span></li>
              <li class="list-group-item"><strong>Quantity:</strong> <span id="preview-quantity"></span></li>
              <li class="list-group-item"><strong>Minimum rental days:</strong> <span id="preview-min-days-rent"></span></li>
              <li class="list-group-item"><strong>Price:</strong> <span id="preview-price"></span></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<style>

.button {
  font: inherit;
  line-height: normal;
  cursor: pointer;
  background: #E8474C;
  color: white;
  font-weight: bold;
  width: auto;
  margin-left: auto;
  font-weight: bold;
  padding-left: 2em;
  padding-right: 2em;
  border-radius: 20px;
  width: 180px;
}

.required {
  border-radius: 20px;
}

.text-input {
  background-color: black;
  color: white; /* optional - this sets the text color to white to improve visibility on a black background */
  border: 1px solid #ccc;
  padding: 10px;
  font-size: 16px;
}

.text-input.file-input input[type="file"] {
  background-color: black;
  color: white;
  padding: 10px;
  border: 1px solid #ccc;
}

.text-input.file-input input[type="file"]::-webkit-file-upload-button {
  padding: 10px;
  margin: 5px;
  border: none;
  background-color: #ccc;
  color: white;
  border-radius: 5px;
  font-weight: bold;
}

.text-input.file-input input[type="file"]::-ms-browse {
  padding: 10px;
  margin: 5px;
  border: none;
  background-color: #ccc;
  color: white;
  border-radius: 5px;
  font-weight: bold;
}

</style>
<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#preview-image').attr('src', e.target.result);
        $('#preview-image').css('display', 'block');
      };

      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#item_photos").change(function () {
    readURL(this);
  });

  $("#item_name").keyup(function () {
    $("#preview-name").text($(this).val());
  });

  $("#item_category").change(function () {
    $("#preview-category").text($(this).val());
  });

  $("#item_description").keyup(function () {
    $("#preview-description").text($(this).val());
  });

  $("#item_postal_code").keyup(function () {
    $("#preview-postal-code").text($(this).val());
  });

  $("#item_quantity").on('input', function () {
    $("#preview-quantity").text($(this).val());
  });

  $("#item_min_days_rent").on('input', function () {
    $("#preview-min-days-rent").text($(this).val());
  });

  $("#item_price").on('input', function () {
    $("#preview-price").text($(this).val());
  });
</script>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <% if @item.picture %>
          <%= image_tag @item.picture, class: "card-img-top", height: 300, width: 400, crop: :fill %>
        <% else %>
          <% @item.photos.each do |photo| %>
            <%= cl_image_tag photo.key, class: "card-img-top", height: 300, width: 400, crop: :fill %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h1><%= @item.name %></h1>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong>Category:</strong> <%= @item.category %></li>
          <li class="list-group-item"><strong>Description:</strong> <%= @item.description %></li>
          <li class="list-group-item"><strong>Postal code:</strong> <%= @item.postal_code %></li>
          <li class="list-group-item"><strong>Quantity:</strong> <%= @item.quantity %></li>
          <li class="list-group-item"><strong>Minimum rental days:</strong> <%= @item.min_days_rent %></li>
          <li class="list-group-item"><strong>Price:</strong> <%= @item.price %> euros per day</li>
        </ul>

        <div class="item-actions mt-3">
          <% unless policy(@item).owner? %>
            <button type="button" class="btn btn-success">
              <%= link_to "Book", new_item_booking_path(@item) %>
            </button>
          <% end %>

          <% if policy(@item).edit? %>
            <button type="button" class="btn btn-warning">
              <%= link_to "Edit", edit_item_path %>
            </button>
          <% end %>

          <% if policy(@item).destroy? %>
            <button type="button" class="btn btn-danger">
              <%= link_to "Delete",
                item_path,
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
              %>
            </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

<div class="reviews">
  <h2>Reviews</h2>
  <% if @reviews.present? %>
    <%= render @reviews %>
  <% else %>
    <p>No reviews yet.</p>
  <% end %>
</div>

<hr>
<div class="see-all">
  <button>
    <%= link_to "See all items", items_path %>
  </button>
</div>

<style>

  .star-rating {
    display: inline-flex;
    align-items: center;
  }
  .star-rating label {
    color: #999;
    font-size: 24px;
    line-height: 1;
    margin-right: 5px;
    cursor: pointer;
  }
  .star-rating .full-star {
    color: #FFD700;
    text-shadow: 1px 1px #555;
  }
  .star-rating .half-star:before {
    content: "\00BD";
    position: relative;
    left: -0.5em;
  }
  .star-rating .empty-star:hover,
  .star-rating .full-star:hover,
  .star-rating .half-star:hover ~ label {
    color: #FFD700;
  }
  .star-rating .full-star.selected,
  .star-rating .half-star.selected ~ .full-star {
    color: #FFD700;
  }
</style>

app/views/items/toggle_favorite.js.erb
var itemId = '<%= @item.id%>';
var likeButton = document.querySelector(`.like-icon[data-id='${itemId}'] i`);
likeButton.classList.toggle('red');